SEX = ["M", "F"]
MEDAL = ["Bronze", "Silver", "Gold"]

SPORT = [
    "Aeronautics",
    "Alpine Skiing",
    "Alpinism",
    "Archery",
    "Art Competitions",
    "Athletics",
    "Badminton",
    "Baseball",
    "Basketball",
    "Basque Pelota",
    "Beach Volleyball",
    "Biathlon",
    "Bobsleigh",
    "Boxing",
    "Canoeing",
    "Cricket",
    "Croquet",
    "Cross Country Skiing",
    "Curling",
    "Cycling",
    "Diving",
    "Equestrianism",
    "Fencing",
    "Figure Skating",
    "Football",
    "Freestyle Skiing",
    "Golf",
    "Gymnastics",
    "Handball",
    "Hockey",
    "Ice Hockey",
    "Jeu De Paume",
    "Judo",
    "Lacrosse",
    "Luge",
    "Military Ski Patrol",
    "Modern Pentathlon",
    "Motorboating",
    "Nordic Combined",
    "Polo",
    "Racquets",
    "Rhythmic Gymnastics",
    "Roque",
    "Rowing",
    "Rugby",
    "Rugby Sevens",
    "Sailing",
    "Shooting",
    "Short Track Speed Skating",
    "Skeleton",
    "Ski Jumping",
    "Snowboarding",
    "Softball",
    "Speed Skating",
    "Swimming",
    "Synchronized Swimming",
    "Table Tennis",
    "Taekwondo",
    "Tennis",
    "Trampolining",
    "Triathlon",
    "Tug-Of-War",
    "Volleyball",
    "Water Polo",
    "Weightlifting",
    "Wrestling",
]
GAMES = [
    "1896 Summer",
    "1900 Summer",
    "1904 Summer",
    "1906 Summer",
    "1908 Summer",
    "1912 Summer",
    "1920 Summer",
    "1924 Summer",
    "1924 Winter",
    "1928 Summer",
    "1928 Winter",
    "1932 Summer",
    "1932 Winter",
    "1936 Summer",
    "1936 Winter",
    "1948 Summer",
    "1948 Winter",
    "1952 Summer",
    "1952 Winter",
    "1956 Summer",
    "1956 Winter",
    "1960 Summer",
    "1960 Winter",
    "1964 Summer",
    "1964 Winter",
    "1968 Summer",
    "1968 Winter",
    "1972 Summer",
    "1972 Winter",
    "1976 Summer",
    "1976 Winter",
    "1980 Summer",
    "1980 Winter",
    "1984 Summer",
    "1984 Winter",
    "1988 Summer",
    "1988 Winter",
    "1992 Summer",
    "1992 Winter",
    "1994 Winter",
    "1996 Summer",
    "1998 Winter",
    "2000 Summer",
    "2002 Winter",
    "2004 Summer",
    "2006 Winter",
    "2008 Summer",
    "2010 Winter",
    "2012 Summer",
    "2014 Winter",
    "2016 Summer",
]
REGION = [
    "Afghanistan, AFG",
    "Albania, ALB",
    "Algeria, ALG",
    "American Samoa, ASA",
    "Andorra, AND",
    "Angola, ANG",
    "Antigua, ANT, Antigua and Barbuda",
    "Argentina, ARG",
    "Armenia, ARM",
    "Aruba, ARU",
    "Australia, AUS",
    "Australia, ANZ, Australasia",
    "Austria, AUT",
    "Azerbaijan, AZE",
    "Bahamas, BAH",
    "Bahrain, BRN",
    "Bangladesh, BAN",
    "Barbados, BAR",
    "Belarus, BLR",
    "Belgium, BEL",
    "Belize, BIZ",
    "Benin, BEN",
    "Bermuda, BER",
    "Bhutan, BHU",
    "Boliva, BOL",
    "Bosnia and Herzegovina, BIH",
    "Botswana, BOT",
    "Brazil, BRA",
    "Brunei, BRU",
    "Bulgaria, BUL",
    "Burkina Faso, BUR",
    "Burundi, BDI",
    "Cambodia, CAM",
    "Cameroon, CMR",
    "Canada, CAN",
    "Canada, NFL, Newfoundland",
    "Cape Verde, CPV",
    "Cayman Islands, CAY",
    "Central African Republic, CAF",
    "Chad, CHA",
    "Chile, CHI",
    "China, HKG, Hong Kong",
    "China, CHN",
    "Colombia, COL",
    "Comoros, COM",
    "Cook Islands, COK",
    "Costa Rica, CRC",
    "Croatia, CRO",
    "Cuba, CUB",
    "Curacao, AHO, Netherlands Antilles",
    "Cyprus, CYP",
    "Czech Republic, BOH, Bohemia",
    "Czech Republic, CZE",
    "Czech Republic, TCH",
    "Democratic Republic of the Congo, COD",
    "Denmark, DEN",
    "Djibouti, DJI",
    "Dominica, DMA",
    "Dominican Republic, DOM",
    "Ecuador, ECU",
    "Egypt, EGY",
    "El Salvador, ESA",
    "Equatorial Guinea, GEQ",
    "Eritrea, ERI",
    "Estonia, EST",
    "Ethiopia, ETH",
    "Fiji, FIJ",
    "Finland, FIN",
    "France, FRA",
    "Gabon, GAB",
    "Gambia, GAM",
    "Georgia, GEO",
    "Germany, SAA",
    "Germany, FRG",
    "Germany, GER",
    "Germany, GDR",
    "Ghana, GHA",
    "Greece, GRE",
    "Greece, CRT, Crete",
    "Grenada, GRN",
    "Guam, GUM",
    "Guatemala, GUA",
    "Guinea, GUI",
    "Guinea-Bissau, GBS",
    "Guyana, GUY",
    "Haiti, HAI",
    "Honduras, HON",
    "Hungary, HUN",
    "Iceland, ISL",
    "India, IND",
    "Indonesia, INA",
    "Iran, IRI",
    "Iraq, IRQ",
    "Ireland, IRL",
    "Israel, ISR",
    "Italy, ITA",
    "Ivory Coast, CIV",
    "Jamaica, JAM",
    "Japan, JPN",
    "Jordan, JOR",
    "Kazakhstan, KAZ",
    "Kenya, KEN",
    "Kiribati, KIR",
    "Kosovo, KOS",
    "Kuwait, KUW",
    "Kyrgyzstan, KGZ",
    "Laos, LAO",
    "Latvia, LAT",
    "Lebanon, LIB",
    "Lesotho, LES",
    "Liberia, LBR",
    "Libya, LBA",
    "Liechtenstein, LIE",
    "Lithuania, LTU",
    "Luxembourg, LUX",
    "Macedonia, MKD",
    "Madagascar, MAD",
    "Malawi, MAW",
    "Malaysia, NBO, North Borneo",
    "Malaysia, MAS",
    "Malaysia, MAL",
    "Maldives, MDV",
    "Mali, MLI",
    "Malta, MLT",
    "Marshall Islands, MHL",
    "Mauritania, MTN",
    "Mauritius, MRI",
    "Mexico, MEX",
    "Micronesia, FSM",
    "Moldova, MDA",
    "Monaco, MON",
    "Mongolia, MGL",
    "Montenegro, MNE",
    "Morocco, MAR",
    "Mozambique, MOZ",
    "Myanmar, MYA",
    "Namibia, NAM",
    "Nauru, NRU",
    "Nepal, NEP",
    "Netherlands, NED",
    "New Zealand, NZL",
    "Nicaragua, NCA",
    "Niger, NIG",
    "Nigeria, NGR",
    "North Korea, PRK",
    "Norway, NOR",
    "Oman, OMA",
    "Pakistan, PAK",
    "Palau, PLW",
    "Palestine, PLE",
    "Panama, PAN",
    "Papua New Guinea, PNG",
    "Paraguay, PAR",
    "Peru, PER",
    "Philippines, PHI",
    "Poland, POL",
    "Portugal, POR",
    "Puerto Rico, PUR",
    "Qatar, QAT",
    "Republic of Congo, CGO",
    "Romania, ROU",
    "Russia, URS",
    "Russia, RUS",
    "Russia, EUN",
    "Rwanda, RWA",
    "Saint Kitts, SKN, Turks and Caicos Islands",
    "Saint Lucia, LCA",
    "Saint Vincent, VIN",
    "Samoa, SAM",
    "San Marino, SMR",
    "Sao Tome and Principe, STP",
    "Saudi Arabia, KSA",
    "Senegal, SEN",
    "Serbia, SRB",
    "Serbia, YUG, Yugoslavia",
    "Serbia, SCG, Serbia and Montenegro",
    "Seychelles, SEY",
    "Sierra Leone, SLE",
    "Singapore, SIN",
    "Slovakia, SVK",
    "Slovenia, SLO",
    "Solomon Islands, SOL",
    "Somalia, SOM",
    "South Africa, RSA",
    "South Korea, KOR",
    "South Sudan, SSD",
    "Spain, ESP",
    "Sri Lanka, SRI",
    "Sudan, SUD",
    "Suriname, SUR",
    "Swaziland, SWZ",
    "Sweden, SWE",
    "Switzerland, SUI",
    "Syria, SYR",
    "Syria, UAR, United Arab Republic",
    "Taiwan, TPE",
    "Tajikistan, TJK",
    "Tanzania, TAN",
    "Thailand, THA",
    "Timor-Leste, TLS",
    "Togo, TOG",
    "Tonga, TGA",
    "Trinidad, TTO, Trinidad and Tobago",
    "Trinidad, WIF, West Indies Federation",
    "Tunisia, TUN",
    "Turkey, TUR",
    "Turkmenistan, TKM",
    "Tuvalu, TUV",
    "UK, GBR",
    "USA, USA",
    "Uganda, UGA",
    "Ukraine, UKR",
    "United Arab Emirates, UAE",
    "Uruguay, URU",
    "Uzbekistan, UZB",
    "Vanuatu, VAN",
    "Venezuela, VEN",
    "Vietnam, VIE",
    "Vietnam, VNM",
    "Virgin Islands, British, IVB",
    "Virgin Islands, US, ISV, Virgin Islands",
    "Yemen, YAR, North Yemen",
    "Yemen, YEM",
    "Yemen, YMD, South Yemen",
    "Zambia, ZAM",
    "Zimbabwe, RHO",
    "Zimbabwe, ZIM",
    "Individual Olympic Athletes, IOA",
    "Refugee Olympic Team, ROT",
    "Unknown, UNK",
]
